# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DTmjo4goGxoFF8nh1TDzoFDBZZ4uckP/TX4CAzeBMvr2WGD/K4gvFt647mcZiNGiEBoK11B3hhUQYZG8KpIITfQn8x5k7bP0KR1Qq0B4NZ/NTyvKUW/M6tpIzinT//Z6JModhypCidZ+mNOTQ8WkoXsLRLSsFtjEOXinI7gizg1thP88fPBvuaxwSeSRs2EhAaq/tyautp0dU+C1FkbOByYidmKYDOx9BzK68t40kGsb4sP+QSE238c3B/nvqz4wSqHQbiKWRk2FZj2/rO1+Du40sExvT1iV1YZEj2qiDcw3SfN93NvOt3aQoQzSIBegasWez+PoJf3xCEb5iE7EiXUVjgzxb8o/mgJpbhb9TRevYd3+uHpXn2iuUt5QEzlaemD/lLpRqtlE8kmBvp0hqy2SP5YOszt/cNI58agJva7tOkGXyHkMuWl+Tn9e3MSaDe6xk8eATWu9LT9P6hj/J6whvASLFPYKGZKlfbdp6Dx1exiKeIbjdGsj4wyJC6CYGqklXjV4axNrxwRm2zyGLJVWOlAdhgBbJPGZ7wjI8+O2Ef0h7qeJ1mMr3y5bbQhfado+Zae4TaAp5U55CNA5wEXjUID8v783tozw8kS3Kcbrlhy+yzDPCbmsFrdbVb1B9NpLgZcRYIPAmQbOCb5e6aIViGTW6gk21l9jnxMuua0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
