travis:
  secure:
    BINSTAR_TOKEN: zj8hKqrm4v5YuCWOd2S9dqzwzYRk3DOXe8ATpxS4lGeAon3Wq2yJN/0yOxEqAXuRZicgK7Ggcs36e/vdfOhfdYiPvrCEtXB2X6UtU7XyEEXhWjdCzqJMTgrjkXcOw5UJau2sMmggJh0PDpBKeIOu+rSO1QWgR7qQ+zjovIDeStcvKH6dmKd1Odc8F0sbjYkzCww6CTBxphYAGN6IXvOiOf00sA1tNhZUWQyzW46BC0OlF991rEA2l9lNVZkKozl8SxXKZw7TgXKdh+WEKxhJOfR5oVnqWQy0UGqLlB//nZ0iPtypOpyCIP3jB7bBKexhzfhopRdoVhV3Pu1n+QIJQ728syKhc5xHTSwRPcnbVg6nIiHSnr6f8RkJS//Flr7hHcRwP6R43iAZTSS8UU5x9lGFngp2chFKWSNqQLeezkEEpBIv5EWGIzz+ve39FztIzxDqghVgRCaNoH3jkIYeGexsEsJ3Zz1yVZlhGsEWpbPrgNzs1tSHuoj6sY42q0j/oM2BrUhQvQhpv/9Nepzu+KSh/diUn4sku6SU4BI0W1mh//F4KK3dgYUWJuTHH4gk+cxcMoaaoSMeOZbxhBBOOnElrpls67EZW+6T+Av4zKll5A365i09JaQBmOXrn/bOaSfuwAIaY1qKYDg/u7rv1u12zZUwx+ozVtjyrLFq2uM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
