travis:
  secure:
    BINSTAR_TOKEN: HJ2fqna6P9VWAAqjne+l+VovAq41enpezPRAGfHnpXJc/KQvPhEv6TKWfTFq95JAz9bc4Viwj2z96gX3nsnxsoS4jFpyyylVfcDde346P7BARvaydCTMSAe67FaBpjK2ldR0gRMjxSs1RpwsB9YvgS+r6SX1te/77Tf4r9xsL30iyClL60aTZ++B385DyMRUMGYJjN0DvfgyIgOct8CloEI2j53iodvMCpPMBW6s2fwgcvxoOBLzVPkKsSo068EGBsB4Vbo++/Naf/qnvnwXNr/mASdvIQVKDqyShLcmOx3aQr9uyNLDUxn4Zkt3xYW0Jvl6eQNutM3nkSJGAm7LCqF27w8S5G4khkIsenHflcT4+3PEKfWBSKsTdi205Z5lN3/J0Tbz56V7ENdFoW9glnrOsqncTkmjHwer8wbMaFOgYwXh4sdgyMv7Oh1PTEPd9Wxw4Frmk7lc+B98+h+cp/epKv01LMqwDGdd0yFETh7Kl3ceP8TfNWrdCgryp9+hdzaxQ5w1GX6970RPzsDKR348FT2dvk1ac2V2aklmtT77/x+4NCRw76xfzONVLdFZI40QnxLwI3ePlfH4Aug2d5mBjBwu461HPFnG5OD3JW/2GK5BVnH0Vak+nw70sMWZxAxEjlWYFodmprrPQxsB9n/tTSSRQBFYFmH+g4KgwRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
