appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: CjFlGg0UKhOCkvGnotuQBD1PVbXSl9+430fCE9ygIpe4t2xp53Wbx/MMfLlsZEGn9TiMAIjv/pM9obXbyr73frdB12ir1Kz+YwZblP5d7FNLr2q6/bt9Yr2uzN34JjqIRp8qLH5AjMM+weVJ6d5uVUA+uBvILek/ueFFhvH7SoLPNptysw5EMT0QOXEDgQcUcT1k/vokKoanBMZ9My5XYkR3JHScwgR2weT0kEp7UwsRzFGPNCMT6yhC82rGtceuYfNDkEhNthp5jKEU0OiPDETh2wWlchfGvJqJiq5VspngxSc1XjN3F7YB9iM4TOWwwjkvPt8ThHb81Dtwd1rRnAXw/qK7RvUr+F7uS3vRI+PfAeJOsOS2xQ/9h9ejeddmwYCZ48WXosSiUmZjt5twKRi8nVcn4e1IBStLG8fFincgkShljhuf75CxYX9/XVwHiS4pWlD+ZfzXJmvzuEiUqizA98Do1yI/fupzli+Nz0KHaSrdbyzEmP61L696bi619y6H9BBkj3CuYirDidmgLiVv9W1n1eV9P0+pLDCzGDkhsH9PhX+YxAF3A4215eJo5/wNmaBpAseWVQg/FLyyk5EXhcD1TXuzIChwetwpGE5TesA5Bt6yqYMEKsElnpLPKNiDuULBJPBs+BecYm01GXCPs1twMFa2o1DoeNXidTU=}
