travis:
  secure:
    BINSTAR_TOKEN: DTmjo4goGxoFF8nh1TDzoFDBZZ4uckP/TX4CAzeBMvr2WGD/K4gvFt647mcZiNGiEBoK11B3hhUQYZG8KpIITfQn8x5k7bP0KR1Qq0B4NZ/NTyvKUW/M6tpIzinT//Z6JModhypCidZ+mNOTQ8WkoXsLRLSsFtjEOXinI7gizg1thP88fPBvuaxwSeSRs2EhAaq/tyautp0dU+C1FkbOByYidmKYDOx9BzK68t40kGsb4sP+QSE238c3B/nvqz4wSqHQbiKWRk2FZj2/rO1+Du40sExvT1iV1YZEj2qiDcw3SfN93NvOt3aQoQzSIBegasWez+PoJf3xCEb5iE7EiXUVjgzxb8o/mgJpbhb9TRevYd3+uHpXn2iuUt5QEzlaemD/lLpRqtlE8kmBvp0hqy2SP5YOszt/cNI58agJva7tOkGXyHkMuWl+Tn9e3MSaDe6xk8eATWu9LT9P6hj/J6whvASLFPYKGZKlfbdp6Dx1exiKeIbjdGsj4wyJC6CYGqklXjV4axNrxwRm2zyGLJVWOlAdhgBbJPGZ7wjI8+O2Ef0h7qeJ1mMr3y5bbQhfado+Zae4TaAp5U55CNA5wEXjUID8v783tozw8kS3Kcbrlhy+yzDPCbmsFrdbVb1B9NpLgZcRYIPAmQbOCb5e6aIViGTW6gk21l9jnxMuua0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
