travis:
  secure:
    BINSTAR_TOKEN: vJcQnQ5UZGychHxcK8cWl+UwCCozIbjiaaTQ1RLi2qtQbVRNueC0/xvx9/50XUeLHsEO5qkXk9zoAMgQn/PG0cmFaL8gpDP5oQc2yL+tveVGdorbnUwerxFaRMFcuPfnLedDgO/ZjFIDPtn5MtItpC1U7zMMjmCmc1pYnynXX4g//873gxIY857Gu43KqPbMPycFU7kTsREHRYMxJs8bdSukjKmqiwfckDAnRD6+1go3wqROXhTwSHU3ILacpBD2qmmmEwXIsSrtdOhHY9vRb68udbI9YAvMmHQ6CIisJa2HQKcynSa2zHJY/LNb/e6gAeIsV7QzjhryDGvkQA6yRkrmlpxq4P1FMvXij/2Ryl9hlIvqQs5NI8WYLCKKIJGCrrp1i81KOEHFsqs7X4qinnGJpC3AK0SA6LQz8RUj0bDHZ7qZ1eaU1UDbMOcpiIWMVsuvF9Gh9Svws4lhnDHe8aaCLBjAk3JLJwzDuz5NmftOjwiQkNB/hxtcZ0Fa2fryYw3P/SakMWjrhb1ktY65qGgUjfB5dE6LwiiW4zrDoMomOJg9HBKdb6VNSmaWtOjrjtHJ8alpMrOAb1LwhMmEQ+1qmvs9XKoqtG776cvSXEipdxCaQE047YAQHoI0yLpaVQEhclc66KS28R2nqSDOn1fZ62LYdUdIK6fL4RXpNC0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
