travis:
  secure:
    BINSTAR_TOKEN: l/PaKtUty4RffTM5RDo+LdeimVZGSrHNU3z5+iT/tvqvIshtLFi9KNg1QIzO9qU4DHQuoLrC1clVKzBT7EMT90u2CN8B23Bq3Sa3cs7TBiW6rkMwAl3zgTt3ibfTveez6ve76tZkNULZpJxPGBd1DG6XobQZzHk18gTj57wwE027rXyyi55ReQEXqp3FTTUCGw9WTVVUYSwNT4F9FL1tn7KMO1aPkznpZd7xvCGU+kolhBksODh4pfRVHjD+mr/qw1KwQirZ1isvb5yz1/iibXDPrOwvjIAMPBH1Op85Hhbr/44ZA3lMFTHCxnFv+PI6xSzd1M9c4fS5jxZDybOEQ9Z9zSKyOaRI7YlffLmlxYa7OZec1B3k396uHYJQMDspkcIVEozfdS2NsAcJB2iQFsnUkbNmB77proL6ztZdLmk3RncP6A3Pcra6ITIzw6ANOJuhc5BhMZ8zyIbT0L/cwYQ1qbsUl+etTxTIQ8IKw0ZrffTv383X+0Dqdnr2JaQv1ztryUCiXFJrp71kyJ6+f1RmVyhou2hDTrOHO4C+bF3yjElvDdnd4TXsJjIiwr1KS1lLP/bwMSBEsgJMG+o9PBg45akHQS+PcaQjs084b4lMeUlYtA514BvYtpNa9HFSzdA8M1rQr7qL8tiWnVWMFkA/Rhkl7u02Af3yLLKUtqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
